# This template is heavily inspired by anthropic's computer use demo
agent:
  templates:
    system_template: |-
      You are a helpful assistant that can interact with a computer to solve tasks.
    instance_template: |-
      <uploaded_files>
      {{working_dir}}
      </uploaded_files>
      I've uploaded a python code repository in the directory {{working_dir}}. Consider the following PR description:

      <pr_description>
      {{problem_statement}}
      </pr_description>

      Can you help me implement the necessary changes to the repository so that the requirements specified in the <pr_description> are met?
      I've already taken care of all changes to any of the test files described in the <pr_description>. This means you DON'T have to modify the testing logic or any of the tests in any way!
      Your task is to make the minimal changes to non-tests files in the {{working_dir}} directory to ensure the <pr_description> is satisfied.
      Follow these steps to resolve the issue:
      1. As a first step, it might be a good idea to find and read code relevant to the <pr_description>
      2. Create a script to reproduce the error and execute it with `python <filename.py>` using the bash tool, to confirm the error
      3. Edit the sourcecode of the repo to resolve the issue
      4. Rerun your reproduce script and confirm that the error is fixed!
      5. Think about edgecases and make sure your fix handles them as well
      Your thinking should be thorough and so it's fine if it's very long.
    next_step_template: |-
      OBSERVATION:
      {{observation}}
    next_step_no_output_template: |-
      Your command ran successfully and did not produce any output.
  tools:
    bundles:
      - path: tools/registry
      - path: tools/edit_anthropic
      - path: tools/review_on_submit_m
    registry_variables:
      USE_FILEMAP: 'true'
      FILEMAP_TEMPLATE: |-
        <NOTE>This file is too large to display entirely. Showing abbreviated version.
        If you cannot immediately identify what code is relevant for your task,
        it's recommended to use `grep` or similar tools to identify relevant line ranges.
        Only use `str_replace editor view --view_range` if you are confident that the view range is relevant to your task.
        </NOTE>

        {filemap}

        <IMPORTANT><NOTE>The above file has been abbreviated.
        If you cannot immediately identify what code is relevant for your task,
        it's recommended to use `grep` or similar tools to identify relevant line ranges.
        Only use `str_replace editor view --view_range` if you are confident that the view range is relevant to your task.
        </NOTE></IMPORTANT>
      SUBMIT_REVIEW_MESSAGES:
        - |
          Thank you for your work on this issue. Please carefully follow the steps below to help review your changes.

          1. If you made any changes to your code after running the reproduction script, please run the reproduction script again.
            If the reproduction script is failing, please revisit your changes and make sure they are correct.
            If you have already removed your reproduction script, please ignore this step.
          2. Remove your reproduction script (if you haven't done so already).
          3. If you have modified any TEST files, please revert them to the state they had before you started fixing the issue.
            You can do this with `git checkout -- /path/to/test/file.py`. Use below <diff> to find the files you need to revert.
          4. Run the submit command again to confirm.

          Here is a list of all of your changes:

          <diff>
          {{diff}}
          </diff>
    enable_bash_tool: true
    parse_function:
      type: function_calling
  history_processors:
    - type: cache_control
      last_n_messages: 2
  hooks:
    - type: repeat_action_mitigator
      warning_messages:
        - base_action_regex: "str_replace_editor view"
          repetition_count: 4
          warning_message: |
            <IMPORTANT>You have been `str_replace_editor view` actions for {{repetition_count}} consecutive times.
            This is inefficient. Please use search operations to locate the context you need, for example
            `grep` or `find`. Using `str_replace_editor view` for more than 10 actions in a row will cause termination!
            </IMPORTANT>

            <IMPORTANT>
            DO NOT use `str_replace_editor view` for the next action!
            </IMPORTANT>
        - base_action_regex: "str_replace_editor view"
          repetition_count: 2
          warning_message: |
            <IMPORTANT>You have been `str_replace_editor view` actions for {{repetition_count}} consecutive times.
            This can be inefficient. Please consider using search operations to locate the context you need, for example
            `grep` or `find`.
            </IMPORTANT>
        - base_action_regex: ".*"
          repetition_count: 4
          warning_message: |
            <IMPORTANT>
            You have been using similar actions to `{{base_command}}` for {{repetition_count}} consecutive times.
            DO NOT use `{{base_command}}` for the next action!
            Maybe you need to find more relevant context first?
            If a command doesn't work several times in a row, think of a different approach.
            </IMPORTANT>
      requery:
        - base_action_regex: ".*"
          repetition_count: 6
          max_requeries: 6
          requery_message_template: |
            <IMPORTANT>
            You have been using similar actions to `{{base_command}}` for {{repetition_count}} consecutive times.
            Your action has been blocked and did not execute. You MUST use a different approach now.
            Similar actions will be blocked again.
            </IMPORTANT>
      terminate:
        - base_action_regex: ".*"
          repetition_count: 8