env:
  deployment:
    image: python:3.11
  post_startup_commands:
    - |
      apt-get update \
      && apt-get install -y --no-install-recommends \
          chromium \
      && rm -rf /var/lib/apt/lists/*
    - "sweer-backend &> /root/tools/sweer/sweer-backend.log &"
agent:
  tools:
    env_variables:
      WINDOW: 100
      OVERLAP: 2
    bundles:
      - path: tools/registry
      - path: tools/defaults
      - path: tools/search
      - path: tools/edit_linting
      - path: tools/submit
      - path: tools/sweer
    parse_function:
      type: thought_action
  history_processors:
    - type: last_n_observations
      n: 5
  model:
    name: human